### ISSUE TITLE
工具安装失败

### ISSUE THREAD

**Issue by NaturezzZ** [jixinpu/aiopstools#13]
File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\pybrain\structure\__init__.py", line 1, in <module>
    from connections.__init__ import *
ModuleNotFoundError: No module named 'connections'

安装时显示成功，当时当使用标程
python examples/ts_period_predict.py --model_name=lr --data_dir='./aiopstools/timeseries_predict/data/timeseries_data.csv' --predict_time=24
时，报以上错误。

**Comment by Nono17** [comment]
> File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\pybrain\structure__init__.py", line 1, in
> from connections.**init** import *
> ModuleNotFoundError: No module named 'connections'
> 
> 安装时显示成功，当时当使用标程
> python examples/ts_period_predict.py --model_name=lr --data_dir='./aiopstools/timeseries_predict/data/timeseries_data.csv' --predict_time=24
> 时，报以上错误。

你好，请问问题是在哪呢
