### ISSUE TITLE
工具安裝失敗

### ISSUE THREAD

**Issue by a791540852** [jixinpu/aiopstools#7]
工具庫本身不支持python3, 但庫需要的依賴包必須使用python3 以上版本?
這似乎沒辦法解決

**Comment by jixinpu** [comment]
哪个包必须使用python3以上的版本？

**Comment by a791540852** [comment]
我的操作系統是windows10 tensorflow

**Comment by jixinpu** [comment]
目前已经添加对python3的支持。
